# Generated by Django 4.1 on 2022-10-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_roll_no', models.IntegerField(max_length=10, unique=True)),
                ('std_name', models.CharField(max_length=60)),
                ('std_class', models.CharField(max_length=25)),
            ],
        ),
    ]
