# Generated by Django 4.1 on 2022-10-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeID', models.IntegerField(max_length=10, unique=True)),
                ('storeName', models.CharField(max_length=60)),
                ('storeSale', models.IntegerField(max_length=10)),
            ],
        ),
    ]
